version: "3"

services:

  signal:
    build: ./signal
    container_name: signal
    restart: always
    environment:
      TZ: Asia/Shanghai
    working_dir: /signal
    ports:
      - 7002:7001
      - 8080:8080
      - 8081:8081
    volumes:
      - ./signal:/signal
      - ~/.m2:/root/.m2
    command: bash script/run.sh
    depends_on:
      - db-accounts
      - db-message
      - db-abuse
      - redis-master
      - redis-slave
      - redis-sentinel
      - minio
      - elasticmq

  db-accounts:
    image: postgres:11
    container_name: db-accounts
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounts_db
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Shanghai
    ports:
      - 5431:5432
    volumes:
      - ./postgres/accounts/data:/var/lib/postgresql/data

  db-message:
    image: postgres:11
    container_name: db-message
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: message_db
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Shanghai
    ports:
      - 5432:5432
    volumes:
      - ./postgres/message/data:/var/lib/postgresql/data

  db-abuse:
    image: postgres:11
    container_name: db-abuse
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: abuse_db
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Shanghai
    ports:
      - 5433:5432
    volumes:
      - ./postgres/abuse/data:/var/lib/postgresql/data

  redis-master:
    image: redis:5
    container_name: redis-master
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./redis/master/data:/data

  redis-slave:
    image: redis:5
    container_name: redis-slave
    restart: always
    command: redis-server --port 6380 --slaveof redis-master 6379
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6380:6380
    volumes:
      - ./redis/slave/data:/data

  redis-sentinel:
    build: ./redis/sentinel
    container_name: redis-sentinel
    restart: always
    ports:
      - 26379:26379
    environment:
      SENTINEL_NAME: mysentinel
      HOST_IP: 127.0.0.1
      TZ: Asia/Shanghai
    volumes:
      - ./redis/slave/data:/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./minio/data:/data
    ports:
      - 9000:9000
    command: server /data

  elasticmq:
    image: softwaremill/elasticmq:1.1.0
    container_name: elasticmq
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./elasticmq/elasticmq.conf:/opt/elasticmq.conf
    ports:
      - 9324:9324
      - 9325:9325

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - signal
